name: Convert Images to WEBP

env:
  IMAGES_DIR: "blog/assets"

on:
  workflow_dispatch:
  push:
    paths:
      - "blog/assets/**"

defaults:
  run:
    shell: bash

jobs:
  convert-to-webp:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install webp tool
        run: sudo apt-get update && sudo apt-get install -y webp

      - name: Determine changed image files
        id: diff
        run: |
          git config core.quotepath false # マルチバイト文字をエスケープしない設定

          changed_files=$(git diff --diff-filter=AM --name-only HEAD^ | grep -E "\.(jpg|jpeg|png|gif)$" || true)

          echo "changed_files=$changed_files" >> $GITHUB_OUTPUT

      - name: Convert images to WEBP
        if: ${{ steps.diff.outputs.changed_files != '' }}
        run: |
          mkdir -p converted # 出力ディレクトリを作成

          echo "${{ steps.diff.outputs.changed_files }}" | while read -r file; do # 変換対象ファイルを1つずつ処理
            output="converted/$(basename "${file%.*}").webp" # 出力ファイル名を設定

            cwebp "$file" -o "$output"
            rm "$file"
            echo "::notice::Converted $file to $output"
          done

      - name: Commit and push changes
        if: ${{ steps.diff.outputs.changed_files != '' }}
        run: |
          git config user.name 'convert-to-webp'
          git config user.email 'convert-to-webp@github.com'

          echo '::notice Changed files are '$(git diff --name-only)
          git add ${{ env.IMAGES_DIR }}/*
          git commit -m 'Convert images to WEBP'
          git push
