name: Convert Images to WEBP

env:
  IMAGES_DIR: "blog/assets"

on:
  workflow_dispatch:
  push:
    paths:
      - "blog/assets/**"

defaults:
  run:
    shell: bash

jobs:
  convert-to-webp:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install webp tool
        run: sudo apt-get update && sudo apt-get install -y webp

      - name: Determine changed image files
        id: diff
        run: |
          git config core.quotepath false # マルチバイト文字をエスケープしない設定

          changed_files=$(git diff --diff-filter=AM --name-only HEAD^ | grep -E "\.(jpg|jpeg|png|gif)$" || true)

          echo "changed_files=$changed_files" >> $GITHUB_OUTPUT

      - name: Convert images to WEBP
        if: ${{ steps.diff.outputs.changed_files != '' }}
        run: |
          mkdir -p converted # 出力ディレクトリを作成

          echo "${{ steps.diff.outputs.changed_files }}" | while read -r file; do # 変換対象ファイルを1つずつ処理
            output="converted/$(basename "${file%.*}").webp" # 出力ファイル名を設定

            cwebp "$file" -o "$output"
            rm "$file"
            echo "::notice::Converted $file to $output"
          done

      - name: Move assets to Cloudflare R2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
        run: |
          for file in converted/*.webp; do
            aws --endpoint-url="https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com" s3 mv "$file" "s3://${R2_BUCKET_NAME}/blog/"
            echo "::notice::Uploaded $file to R2"
          done
