name: Upload Assets to Cloudflare R2

on:
  workflow_dispatch:
  push:
    paths:
      - 'blog/assets/**'

defaults:
  run:
    shell: bash

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync assets to Cloudflare R2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
        run: aws --endpoint-url=https://${{ env.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com s3 sync blog/assets s3://${{ env.R2_BUCKET_NAME }}/blog/assets
